/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlinemanagement;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author MM
 */
public class Management extends javax.swing.JFrame {

    /**
     * Creates new form Management
     */
    public Management() {
        initComponents();
         setBounds(250,20,900,700);
         //Flight Icon
         ImageIcon Image1=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("international.png")));
         Image myimage= Image1.getImage(); 
         Image img=myimage.getScaledInstance(Flighticon.getWidth(), Flighticon.getHeight(), Image.SCALE_SMOOTH);
         ImageIcon i=new ImageIcon(img);
         Flighticon.setIcon(i);
        //PassengerIcon
         ImageIcon Image2=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("traveler.png")));
         Image myimage2= Image2.getImage(); 
         Image img2=myimage2.getScaledInstance(Passengericon.getWidth(), Passengericon.getHeight(), Image.SCALE_SMOOTH);
         ImageIcon i2=new ImageIcon(img2);
         Passengericon.setIcon(i2);
         //TicketIcon
         ImageIcon Image3=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("airplane-ticket.png")));
         Image myimage3= Image3.getImage(); 
         Image img3=myimage3.getScaledInstance(Ticketicon.getWidth(), Ticketicon.getHeight(), Image.SCALE_SMOOTH);
         ImageIcon i3=new ImageIcon(img3);
         Ticketicon.setIcon(i3);
          //CancelletionIcon
         ImageIcon Image4=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("cancel.png")));
         Image myimage4= Image4.getImage(); 
         Image img4=myimage4.getScaledInstance(Cancellationicon.getWidth(), Cancellationicon.getHeight(), Image.SCALE_SMOOTH);
         ImageIcon i4=new ImageIcon(img4);
         Cancellationicon.setIcon(i4);
         //ExitIcon
         ImageIcon Image5=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("exit.png")));
         Image myimage5= Image5.getImage(); 
         Image img5=myimage5.getScaledInstance(Exiticon.getWidth(), Exiticon.getHeight(), Image.SCALE_SMOOTH);
         ImageIcon i5=new ImageIcon(img5);
         Exiticon.setIcon(i5);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        FlightsBtn = new javax.swing.JButton();
        PassengersBtn = new javax.swing.JButton();
        TicketsBtn = new javax.swing.JButton();
        CancelletionBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Flighticon = new javax.swing.JLabel();
        Passengericon = new javax.swing.JLabel();
        Ticketicon = new javax.swing.JLabel();
        Cancellationicon = new javax.swing.JLabel();
        Exiticon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setUndecorated(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        FlightsBtn.setBackground(new java.awt.Color(0, 102, 255));
        FlightsBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        FlightsBtn.setForeground(new java.awt.Color(153, 204, 255));
        FlightsBtn.setText("Flights");
        FlightsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightsBtnMouseClicked(evt);
            }
        });
        FlightsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightsBtnActionPerformed(evt);
            }
        });

        PassengersBtn.setBackground(new java.awt.Color(0, 102, 255));
        PassengersBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PassengersBtn.setForeground(new java.awt.Color(153, 204, 255));
        PassengersBtn.setText("Passengers");
        PassengersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengersBtnMouseClicked(evt);
            }
        });

        TicketsBtn.setBackground(new java.awt.Color(0, 102, 255));
        TicketsBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TicketsBtn.setForeground(new java.awt.Color(153, 204, 255));
        TicketsBtn.setText("Tickets");
        TicketsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TicketsBtnMouseClicked(evt);
            }
        });

        CancelletionBtn.setBackground(new java.awt.Color(0, 102, 255));
        CancelletionBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CancelletionBtn.setForeground(new java.awt.Color(153, 204, 255));
        CancelletionBtn.setText("Cancelletion");
        CancelletionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelletionBtnMouseClicked(evt);
            }
        });

        ExitBtn.setBackground(new java.awt.Color(51, 102, 255));
        ExitBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(153, 204, 255));
        ExitBtn.setText("Exit");
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(0, 102, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 204, 255));
        jLabel2.setText("                        Air Blue Airlines");
        jLabel2.setOpaque(true);

        Flighticon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlighticonMouseClicked(evt);
            }
        });

        Passengericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengericonMouseClicked(evt);
            }
        });

        Ticketicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TicketiconMouseClicked(evt);
            }
        });

        Cancellationicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancellationiconMouseClicked(evt);
            }
        });

        Exiticon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExiticonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CancelletionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TicketsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PassengersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FlightsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(253, 253, 253)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Exiticon, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(Ticketicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Passengericon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Flighticon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cancellationicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(FlightsBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Flighticon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Passengericon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PassengersBtn)
                        .addGap(53, 53, 53)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ticketicon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(TicketsBtn)))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(CancelletionBtn)
                        .addGap(78, 78, 78)
                        .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Cancellationicon, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(Exiticon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PassengersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengersBtnMouseClicked
        new Passengers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PassengersBtnMouseClicked

    private void FlightsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightsBtnMouseClicked
       new Flights().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_FlightsBtnMouseClicked

    private void TicketsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TicketsBtnMouseClicked
       new TicketBooking().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_TicketsBtnMouseClicked

    private void CancelletionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelletionBtnMouseClicked
        new Cancelletion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelletionBtnMouseClicked

    private void FlightsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlightsBtnActionPerformed

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
      System.exit(0);
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void FlighticonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlighticonMouseClicked
        new Flights().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_FlighticonMouseClicked

    private void PassengericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengericonMouseClicked
      new Passengers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PassengericonMouseClicked

    private void TicketiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TicketiconMouseClicked
       new TicketBooking().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_TicketiconMouseClicked

    private void CancellationiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancellationiconMouseClicked
        new Cancelletion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancellationiconMouseClicked

    private void ExiticonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExiticonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExiticonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cancellationicon;
    private javax.swing.JButton CancelletionBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel Exiticon;
    private javax.swing.JLabel Flighticon;
    private javax.swing.JButton FlightsBtn;
    private javax.swing.JLabel Passengericon;
    private javax.swing.JButton PassengersBtn;
    private javax.swing.JLabel Ticketicon;
    private javax.swing.JButton TicketsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
